name: env-asr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fsspec
  - ipykernel
  - openssh
  - librosa
  - azure-ai-ml
  - azure-identity
  - azureml
  - azure-core
  - scikit-learn
  - pandas
  - numpy<2.0
  - matplotlib
  - seaborn
  - pyspark
  - pip
  - pip:
    - azureml-core
    - azureml-featurestore
    - azureml-mlflow
    - mlflow